name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Check Formatting
        run: forge fmt --check

      - name: Run Forge Tests
        run: forge test

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Slither
        run: pip install slither-analyzer

      - name: Run Slither Security Analysis
        run: slither . --ignore-compile